#pragma once

#include <vector>
#include <array>
#include <assert.h>
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <iostream>
#include <cstring>
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#include <string>
#include <map>
#include <fstream>
#include <assert.h>
#include "imgui_impl/Log.h"
#include <stdexcept>
#include <iostream>
#include <stdexcept>
#include <functional>
#include <cstdlib>
#include <set>
#include <algorithm>
#include <chrono>
#include <cstring>
#include <set>
#include <unordered_map>
#include <iostream>
#include <stdexcept>
#include <functional>
#include <cstdlib>
#include <set>
#include <algorithm>
#include <chrono>
#include <cstring>